/*
 * This source file was generated by the Gradle 'init' task
 */

package chauffeur;

import chauffeur.controller.Controller;
import chauffeur.discord.Discord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;

@SpringBootApplication
// @ComponentScan(basePackages = { "chauffeur.controller" })
public class App {
  static final Logger logger = LoggerFactory.getLogger(App.class);

  public static void main(String[] args) {
    if (args.length < 1) {
      logger.error("Please specify the process to run within the parameter: server or worker");

      return;
    }

    switch (args[0]) {
    case "server" -> new SpringApplicationBuilder(Controller.class).run(args);
    case "worker" -> new SpringApplicationBuilder(Discord.class).web(WebApplicationType.NONE)
        .run(args);
    default -> logger.error(
        "Unknown process: {}. Please specify the process to run within the parameter: server or worker",
        args[0]);
    }
  }
}
