/*
 * This source file was generated by the Gradle 'init' task
 */
package chauffeur;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.annotation.ComponentScan;

import chauffeur.controller.Controller;
import chauffeur.discord.Discord;

@SpringBootApplication
@ComponentScan(basePackages = { "chauffeur.controller" })
public class App {
    static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        String profile = System.getProperty(
                "spring.profiles.active",
                System.getenv().getOrDefault("SPRING_PROFILES_ACTIVE", "server"));
        logger.info("Active profile: {}", profile);

        switch (profile) {
            case "server":
                new SpringApplicationBuilder(Controller.class).profiles("server").run(args);
                break;
            case "worker":
                new SpringApplicationBuilder(Discord.class).web(WebApplicationType.NONE).profiles("worker").run(args);
                break;
            default:
                logger.error("Unknown profile: {}", profile);
        }
    }
}
