/*
 * This source file was generated by the Gradle 'init' task
 */
package chauffeur;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = { "chauffeur" })
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
