/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Spring Boot plugin
    id("org.springframework.boot") version "3.4.5"
    id("io.spring.dependency-management") version "1.1.4"
    id("java")

}

repositories {
    mavenCentral() // Use Maven Central for resolving dependencies.
}

val mockitoAgent = configurations.create("mockitoAgent")

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.mockito)
    testImplementation("org.mockito:mockito-junit-jupiter:5.17.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    
    mockitoAgent(libs.mockito) { isTransitive = false }


    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.springframework.boot:spring-boot-starter:3.4.5")
    implementation("org.springframework.boot:spring-boot-starter-web:3.4.5")
    implementation("org.springframework.boot:spring-boot-starter-validation:3.4.5")
    implementation("org.springframework.boot:spring-boot-starter-test:3.4.5")
    implementation("de.kherud:llama:4.1.0")

    implementation("org.jsoup:jsoup:1.20.1")
    implementation("com.fasterxml.jackson.core:jackson-core:2.19.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "chauffeur.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform() // for unit tests.
    jvmArgs("-javaagent:${mockitoAgent.singleFile}")
}

tasks.bootJar {
    manifest {
        attributes(
            "Implementation-Title" to project.name,
            "Implementation-Version" to project.version,
            "Implementation-Vendor" to "vin-rmdn"
        )
    }
}